services:
  postgres:
    container_name: ms-postgresql
    image: postgres
    environment:
      POSTGRES_USER: cass
      POSTGRES_PASSWORD: password
      POSTGRES_DB:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - microservices-net
    restart: unless-stopped

    # pgadmin:
    #   container_name: ms-pgadmin
    #   image: dpage/pgadmin4
    #   environment:
    #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
    #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    #     PGADMIN_CONFIG_SERVER_MODE: 'False'
    #   volumes:
    #     - pgadmin:/var/lib/pgadmin
    #   ports:
    #     - 5050:80
    #   networks:
    #     - microservices-net
    #   restart: unless-stopped

  mongodb:
    container_name: ms-mongo
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - microservices-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: cass
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped

  mongo-express:
    container_name: ms-mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cass
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    restart: always

  mail-dev:
    container_name: ms-maildev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ms-zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - microservices-net

  kafka:
      image: confluentinc/cp-kafka:latest
      container_name: ms-kafka
      ports:
        - "9092:9092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      networks:
        - microservices-net


networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  mongo:
  # pgadmin: